### ISSUE TITLE
Publish the guide at std-dev-guide.rust-lang.org

### ISSUE THREAD

**Issue by KodrAus** [rust-lang/std-dev-guide#12]
This is a tracking issue for making the `std-dev-guide` available via GitHub Pages on `std-dev-guide.rust-lang.org` (consistent with `rustc-dev-guide.rust-lang.org`).

We now have a `gh-pages` branch with a `index.html` at the root. There's also a `CNAME` in our main branch, but this isn't being deployed to the `gh-pages` branch yet. I'm guessing we'll need to do that.

cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
I've added this to my todo list for Friday.

**Comment by Mark-Simulacrum** [comment]
Done!

**Comment by KodrAus** [comment]
That's great news! Thanks @Mark-Simulacrum
