### ISSUE TITLE
Maintenance of the guide

### ISSUE THREAD

**Issue by camelid** [rust-lang/std-dev-guide#2]
Should WG-rustc-dev-guide have permissions to maintain the std-dev-guide as well? It seems that only T-libs has permissions currently.

**Comment by KodrAus** [comment]
@camelid I think it was initially set up with just `T-libs`, but adding `WG-rustc-dev-guide` sounds like a good idea to me :+1:

cc @Mark-Simulacrum

**Comment by camelid** [comment]
Maybe we should rename WG-rustc-dev-guide to WG-dev-guide or WG-dev-guides...

**Comment by Mark-Simulacrum** [comment]
I do not mind expanding the set, but it seems preferable to have a separate team in rust-lang/team, potentially with significantly overlapping membership.

**Comment by camelid** [comment]
> but it seems preferable to have a separate team in rust-lang/team, potentially with significantly overlapping membership.

I think it would be better to start with one team, and split off another if needed. Having two separate teams adds too much complexity IMO. The rustc-dev-guide and the std-dev-guide will still be fairly similar; IIUC it's just a way to split up the content so the rustc-dev-guide doesn't get too big.

**Comment by Mark-Simulacrum** [comment]
I disagree pretty strongly. I'm pretty sure there is almost zero overhead, and generally it is much cleaner to keep permissions tightly scoped. It also seems highly likely that folks working on the rustc dev guide and std dev guide may diverge over time.

**Comment by camelid** [comment]
One issue I see with splitting stdlib stuff into its own repo is that we'll then have to somehow sync up the infrastructure (like line-length checking, link checking, date checking, etc.).

**Comment by camelid** [comment]
> I'm pretty sure there is almost zero overhead

If WG-std-dev-guide didn't have its own meeting (at least not for the first bit), then I think it would be low overhead. Would WG-std-dev-guide have its own meeting? If we did want to have meetings for it, maybe we could have both WGs meet together?

**Comment by yaahc** [comment]
Just a heads up, we're planning on discussing std-dev-guide maintenance during our next T-libs meeting

https://rust-lang.zulipchat.com/#narrow/stream/259402-t-libs.2Fmeetings/topic/Meeting.202022-06-01

**Comment by JohnTitor** [comment]
Now some more teams including wg-rustc-dev-guide added to review the guide: https://rust-lang.zulipchat.com/#narrow/stream/196385-t-compiler.2Fwg-rustc-dev-guide/topic/consider.20the.20review.20process/near/290964240

**Comment by yaahc** [comment]
I think that means this issue is resolved :tada:
