### ISSUE TITLE
Document `// SAFETY:` comments.

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/std-dev-guide#20]
We should document what we expect from `// Safety: ..` comments.

See also https://github.com/rust-lang/rust/issues/66219

**Comment by poliorcetics** [comment]
Where would this go in the dev guide ? I can write something but I don't know the guide well enough to have an idea of where I should put it.

**Comment by JohnTitor** [comment]
I think under https://std-dev-guide.rust-lang.org/documentation/summary.html would be fine.
